# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-11 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(blank=True, max_length=250, null=True)),
                ('queue', models.IntegerField()),
            ],
        ),
    ]
