# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-11 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modem', '0004_auto_20180111_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(blank=True, choices=[('F', 'F'), ('S', 'S'), ('Q', 'Q'), ('R', 'R'), ('A', 'A')], max_length=3, null=True),
        ),
    ]
