# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-12 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modem', '0008_contact_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_prospera',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(blank=True, choices=[('N', 'N'), ('C', 'C')], default='N', max_length=3, null=True),
        ),
    ]
