# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Nombre de la organizacion')),
            ],
        ),
        migrations.AlterModelOptions(
            name='manageruser',
            options={'verbose_name': 'Manager', 'verbose_name_plural': 'Managers'},
        ),
        migrations.RemoveField(
            model_name='manageruser',
            name='org_name',
        ),
        migrations.RemoveField(
            model_name='manageruser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='manager',
        ),
        migrations.AddField(
            model_name='manageruser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manageruser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='manageruser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='manageruser',
            name='is_admin',
            field=models.BooleanField(default=True, verbose_name='Administrador'),
        ),
        migrations.AddField(
            model_name='manageruser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='manageruser',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
        migrations.AddField(
            model_name='manageruser',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manageruser',
            name='username',
            field=models.CharField(default='username', max_length=50, unique=True, verbose_name='Nombre de usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='manageruser',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Org', verbose_name='Manager'),
        ),
        migrations.AddField(
            model_name='normaluser',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Org', verbose_name='Manager'),
        ),
    ]
